### PR TITLE
if not self.strict, ignore a /Prev entry with the value 0 in the trailer

### LINKED ISSUE #530: A certain PDF File triggers OSError: [Errno 22] Invalid argument
Hello,

This [file](https://drive.google.com/open?id=1JduH56YX7nxFiRF25V8ZWwbyCa0IQvpv) is giving me trouble when attempting to simply create a PdfFileReader object

Code:
```
with open('./media/NTB - LOI.pdf', 'rb') as input:
  PyPDF2.PdfFileReader(input)
```

Error:

```
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/home/vershimaajo/gigarbox_academia/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1084, in __init__
    self.read(stream)
  File "/home/vershimaajo/gigarbox_academia/venv/lib/python3.6/site-packages/PyPDF2/pdf.py", line 1883, in read
    stream.seek(-11, 1)
OSError: [Errno 22] Invalid argument
```

Thanks for assistance!

### PR DESCRIPTION
**Pull request by vashek**
closes #530

### CODE REVIEW

**Comment by MartinThoma** [comment]
There is currently no unit test for that part. Could you add one?

**Comment by vashek** [comment]
> There is currently no unit test for that part. Could you add one?

Here you go.

**Comment by MartinThoma** [comment]
Very nice! Thank you for your contribution :hugs:

**Comment by vashek** [comment]
> Very nice! Thank you for your contribution 🤗

Thank you for reviving the project! :)

**Comment by MartinThoma** [comment]
I'm not sure yet when I will create the next release, but latest in May. Probably end of next week - if nobody complains about it, I'd rather release often :-) 

You seem to be very experienced, so I guess you already know that you can install the latest PyPDF2 version via `pip install git+https://github.com/py-pdf/PyPDF2.git` in case you want to be on the pre-release version :-)

**Comment by vashek** [comment]
> I'm not sure yet when I will create the next release, but latest in May. Probably end of next week - if nobody complains about it, I'd rather release often :-)

That's perfectly fine with me, thanks!

> You seem to be very experienced, so I guess you already know that you can install the latest PyPDF2 version via `pip install git+https://github.com/py-pdf/PyPDF2.git` in case you want to be on the pre-release version :-)

Actually, I generally use `pipenv` for my projects and what I do when I need a version with some unreleased or even unmerged fix is that I specify the package in the `Pipfile` like this, for example:

```
[packages]
pillow = "~=8.2.0"
pypdf2 = {editable = true, ref = "bugfix/gss-1789-rollup", git = "https://github.com/vashek/PyPDF2.git"}
```

(just in case it helps anyone...)

**Pull request merged**
