### PR TITLE
Initial support for CMap character translation

### PR DESCRIPTION
**Pull request by Upliner**
Should solve issue #168

### CODE REVIEW

**Comment by mstamy2** [comment]
Experiencing a few issues with this PR. Some text in the output is duplicated.

I'll provide the failing document shortly if needed.

**Comment by yardensachs** [comment]
Any news about this one?

**Comment by massimosala** [comment]
Upliner, the patch seems good.

Only one suggestion: you discard a line feed evaluating
operator == b_('"')

Please add a comment in the code to explain.

**Comment by technic** [comment]
This is important functionality, please consider merging.

**Comment by MartinThoma** [comment]
Have you seen #464 ? Is #464 a superset of this PR? What do you think about it?

**Comment by MartinThoma** [comment]
Would you mind fixing the merge conflicts of this PR?

**Comment by MartinThoma** [comment]
Thank you for this PR :heart: 

@pubpub-zz has put a lot of effort in bringing similar improvements to PyPDF2. As I believe that we have everything already merged, I'll close this PR.

**Pull request closed without merging**
