### PR TITLE
Pubpub zz extract text

### PR DESCRIPTION
**Pull request by MartinThoma**
This PR will not get merged - the main PR is https://github.com/py-pdf/PyPDF2/pull/881

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@MartinThoma, for depreciation warning handling why not using
`@pytest.mark.filterwarnings('ignore::PendingDeprecationWarning')`
for readability ?

**Comment by MartinThoma** [comment]
Filtering the warnings just ignores them. But having the other syntax ensures that there is a warning.

I thought about just using the new syntax everywhere in the tests for readability. But I'd rather do this in another PR. This one is quite massive already; I try to keep it only to the text improvements. This makes it easier for people to review it (or check the squashed commit in the commit history afterwards)

**Comment by MartinThoma** [comment]
I'll now re-run the benchmark to ensure that I didn't mess up.

I'll also check if there are minor stylistic changes. I guess I'll merge this one in 1-2 hours :-) This is so exiting. I think this is the most massive improvement to PyPDF2 since 2016 :partying_face:

**Comment by pubpub-zz** [comment]
😊😊

**Comment by MartinThoma** [comment]
@pubpub-zz I don't think anybody would want the old extraction function `_extract_text_old` as your new function seems to be better across all examples. I would drop it. What do you think about it?

**Comment by pubpub-zz** [comment]
In case of a non detected regression I wanted people to fold back. This is why I left it.

**Comment by MartinThoma** [comment]
Ok, then I'll leave it for the moment + mention it in the changelog.

Regarding `PdfWithXForm.pdf`: Where does that come from? There is a name of a person in there which makes we worry about privacy laws.

**Comment by pubpub-zz** [comment]
PdfWithXForm.pdf was the example from the PR. I agree that There could be some issue with the address that may be a good one... I would propose you to replace it with 2201.00029.pdf that also includes XForms (This is why it was 0% before). Note that in this latest file some XForm images are missing inducing some warnings

**Pull request merged**
