### PR TITLE
Feature/ascii85 off by one

### PR DESCRIPTION
**Pull request by speedplane**
ASCII 85 can represent 2^32-1. This error was causing validations to break.

Note that this merge requires #332 to be merged first to be a nice clean merge.

### CODE REVIEW

**Comment by vstoykov** [comment]
It will be best if this changes was against this projects master instead of your master, because will be easier to be merged even if the changes from your other PR are not accepted.

**Comment by MartinThoma** [comment]
I think this is related to https://github.com/mstamy2/PyPDF2/issues/312

**Comment by MartinThoma** [comment]
> Note that this merge requires https://github.com/py-pdf/PyPDF2/pull/332 to be merged first to be a nice clean merge.

Why that?

**Comment by MartinThoma** [comment]
Does anybody happen to have a PDF file with `/ASCII85Decode` data streams that we could use for testing?

**Comment by MartinThoma** [comment]
The current state is not compatible with main. Would you mind to fix the merge conflicts?

**Comment by MartinThoma** [comment]
I think the main point of this PR was already adressed elsewhere.

**Pull request closed without merging**
