### PR TITLE
Example of hierarchical TOC from several pdf files

### PR DESCRIPTION
**Pull request by vb64**

### CODE REVIEW

**Comment by MartinThoma** [comment]
I just see a markdown file here which is added. Why was it added? Did you maybe forget to add / commit / push something?

**Comment by vb64** [comment]
I read this [file](https://github.com/mstamy2/PyPDF2/blob/master/Sample_Code/README.txt):

> Feel free to add any type of PDF file or sample code, either by
> ...
> 2) including it in a pull request on GitHub

I made pull request with link to my project that use PyPDF2 for creating hierarchical TOC from several pdf files.

If this example not suitable, just close this PR.

**Comment by MartinThoma** [comment]
Ah, gotcha!

What do you think about adding a "Links" section in the `Sample_Code/Readme.txt` instead of adding a file?

**Comment by vb64** [comment]
I think such section with brief description for each href will be useful.

**Comment by MartinThoma** [comment]
Thank you for your contribution!

**Pull request merged**
