### PR TITLE
ENH: Background argument and auto-rotation when merging pages

### PR DESCRIPTION
**Pull request by hvbtup**
These changes extend the merging capabilities: 
1) to auto-rotate the second page if first page and second page have different orientation.
2) to add the second page's content to the background (behind) of the first page instead of on top of it.

Together, thsi allows easy adding of a watermark PDF page with a content like "Top Secret" to a source PDF independent of the source PDF's orientation (the text on the watermark should go diagonal from bottom left to top right)

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you for your contribution :heart: 

Since you've opened this PR, PyPDF2 was dormant for a long time. I'm sorry that you didn't receive feedback. With the new interface for adding transformations to a single page / merging, I think this is no longer necessary.

I'll close it for this reason. Please let me know if you still would like the new method to be in PyPDF2.

**Comment by hvbtup** [comment]
@MartinThoma Please take another close look at the PR:

The current API doesn't support creating true watermarks, because - as the doc say: The parameter page's content stream will be added to the end of this page's content stream, meaning that it will be drawn after, or "on top" of this page.

So, the current API only supports kind of stamping, but not watermarking.

**Comment by MartinThoma** [comment]
Thank you for the clarification! Now I've got it :-)

**Comment by MartinThoma** [comment]
I just gave it a second thought:

```python
# watermark
image_page.merge_page(content_page)

# stamp
content_page.merge_page(image_page)
```

@hvbtup Wouldn't that be possible? Is there a drawback of doing it like this?

**Comment by hvbtup** [comment]
> Wouldn't that be possible? Is there a drawback of doing it like this?

I really doubt that would work. I don't know how PyPDF2 works internally, but I assume that there is a huge difference between a PDF (and the correponding pages) opened for reading and those opened for writing.

**Pull request closed without merging**
