### PR TITLE
MAINT: Split generic.py

### PR DESCRIPTION
**Pull request by MartinThoma**

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@MartinThoma,
  Your reorganisation looks good. I like the idea of referencing the base types in __init__. However, You should also import directly the classes from _base in generic to get their reference in there in order to keep compatiblity with previous versions.

**Comment by MartinThoma** [comment]
@pubpub-zz I've made another split. I'm not 100% happy as "utils" is super generic (and thus unclear what should be in there), but I hope that this change makes it easier to get an overview of what is in `generic`

I've added `__all__` to export the names explicitly. What do you think so far?

**Comment by pubpub-zz** [comment]
> @pubpub-zz I've made another split. I'm not 100% happy as "utils" is super generic (and thus unclear what should be in there), but I hope that this change makes it easier to get an overview of what is in `generic`
> 
> The split should also make it easier to avoid cyclic imports
> 
> I've added `__all__` to export the names explicitly. What do you think so far?

It looks good.
I would just rename generic/_utils.py : it is quite confusing with ./_utils.py ; what about generic/_functions.py ?

**Comment by MartinThoma** [comment]
image

**Comment by pubpub-zz** [comment]
Do you have the SVG version ?

**Comment by MartinThoma** [comment]
I've generated it with 

```
pyreverse -p . -o pdf PyPDF2/generic.py -k 
```

I also looked at https://github.com/Technologicat/pyan - but sadly, that was way to verbose / buggy (and it's no longer maintained)

**Comment by MartinThoma** [comment]
This is the full version: [classes_overview_full.pdf](https://github.com/py-pdf/PyPDF2/files/9331068/classes_.pdf)

**Comment by MartinThoma** [comment]
I re-did the PR because I was uncertain where the conflict came from: https://github.com/py-pdf/PyPDF2/pull/1229

**Pull request closed without merging**
