### PR TITLE
Merge main ours

### PR DESCRIPTION
**Pull request by MartinThoma**
In order to make the `2.0.0-dev` branch become the new `main` branch, I would do this:

```
git merge main -s ours
```

After that, merging the 2.0.0-dev branch into main (with a merge-commit) should be automatically possible.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Initially, I wanted to get a couple of big shots done to have a great 2.0.0 release with nice new features. However, I do see that the fact that `2.0.0-dev` is currently the branch to work on is confusing. For this reason, I thought about this procedure:

1. **Phase PyPDF2 1.X support out**: Wait until 29th of May. If there were any breaking changes (e.g. internal deprecation warnings), I would fix those in a 1.29.X release.
2. **main branch**: Make the current state of `2.0.0-dev` become the new `main` (e.g. by merging this PR + then merging `2.0.0-dev` back into main)
3. **Release PyPDF2 2.0.0** latest on 1st of June and continue with a normal development workflow.
4. **Actual deprecations**: Although several of the warnings say that some functions become deprecated, I would keep many around for a long time (e.g. until 1st of June 2023) so that people / articles / tutorials have time to adjust. Especially the `PdfFileReader`. But I would likely drop tests for those "adapter classes / methods / functions".

I've also added version support in readthedocs:

* https://pypdf2.readthedocs.io/en/1.27.12/
* https://pypdf2.readthedocs.io/en/1.28.2/

I would keep the latest patch version for each minor version on readthedocs.

@MasterOdin Do you think that is an acceptable way to continue?

**Comment by MasterOdin** [comment]
I think it would make sense to do the following immediately:
1. Create a branch `1.x` from `main`
2. Merge `main` into `2.0.0-dev`
3. Merge `2.0.0-dev` into `main`

Then, any new commits either go:
* Commit to `main`, optionally backport to `1.x`
* Commit to `1.x`

Thus, we never go from `1.x` -> `main`, and avoid any painful merge conflicts for the default branch, especially given the amount of BC breakage happening in `2.0.0-dev`. I find it infinitely easier to backport things than forward port.

**Comment by MartinThoma** [comment]
That's an excellent plan! I'm about to do it :hourglass_flowing_sand: 

* https://github.com/py-pdf/PyPDF2/tree/1.x

**Comment by MartinThoma** [comment]
I merged https://github.com/py-pdf/PyPDF2/pull/859 into main. I hope I didn't mess up :see_no_evil: 

Next steps:

1. Fix the warnings when running the tests (mostly by switching to the new syntax, but I also want to add a few tests for the core parts that got deprecated to ensure I didn't accidentally remove something like PdfFileReader)
2. Update the merge targets of several existing PRs which currently might point to 2.0.0-dev
3. Support people who are still on an older version

I'm not exactly sure yet when to make the 2.0.0 release.

**Comment by MasterOdin** [comment]
> Actual deprecations: Although several of the warnings say that some functions become deprecated, I would keep many around for a long time (e.g. until 1st of June 2023) so that people / articles / tutorials have time to adjust. Especially the PdfFileReader. But I would likely drop tests for those "adapter classes / methods / functions".

Should the deprecation warning messages then be updated to say `3.0.0` instead of `2.0.0` for the stuff that'll stick around into the `2.0.0` release?

**Pull request merged**
