### PR TITLE
Remove star imports

### PR DESCRIPTION
**Pull request by MartinThoma**
Closes #741

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@MartinThoma 
I have a concern about the change introduced  : the imports you have corrected are now using absolute name PyPDF2. often for development purpose I'm duplicating the pypdf2 in order to compare the behavior before and after the change. With absolute name this is no more possible. PEP 8 accepting relative path, can you consider the request to stay with relative path?

**Comment by MartinThoma** [comment]
Sure! However, I don't understand the problem.

Do you know that you can install PyPDF2 from the local folder via "pip install -e ."? Does that solve the issue?

**Comment by pubpub-zz** [comment]
@MartinThoma 
My point does not deal with final installation using pip, during development.
This is my scenario:
as a standard I have the PyPDF2 folder which code I use through "import PyPDF2"
very often, when I'm developping/coding some changes, I need to compare results with original code, Thoses changes are written in a copy named PyPDF2b which called through import PyPDF2b.
that way I can easily get some comparison between code behaviors or quickly compare some tracing.
pdf1 = PyPDF2.PdfFileReader(fn)
pdf2 = PyPDF2b.PdfFileReader(fn)

Do you understand my approach?

**Comment by MartinThoma** [comment]
Ah, interesting. I think I get it and I'll use relative imports again 👍 thanks for helping me understand.

I'm currently sick with fever and cannot concentrate. It will take at least a week until I undo it.

**Comment by pubpub-zz** [comment]
Sorry to hear that. Sure it is covid... still in the air
Get better

**Comment by MartinThoma** [comment]
@pubpub-zz See https://github.com/py-pdf/PyPDF2/pull/875 for the PR. I guess that making everything a relative import is better than just restoring the old state with mixed absolute/relative imports?

**Comment by pubpub-zz** [comment]
I was about to ask what was your preference in order to prepare the PR 😂
Your change looks perfect for me.

Just a last question : there is still some local imports in some functions : do you think we should move them to the top ?

**Comment by MartinThoma** [comment]
Yes, I feel a lot better today - thanks for asking 🤗 yesterday I had over 39°C fever; compared to that I feel fabulous 😁

> Just a last question : there is still some local imports in some functions : do you think we should move them to the top ?

In general, I'd say "yes". The question is if we get circular imports. I think that was the reason for moving the imports into the functions

**Pull request merged**
