### PR TITLE
Improve Python3 compatibility and image extraction script

### PR DESCRIPTION
**Pull request by sylvainpelissier**
More color spaces recognized.

### CODE REVIEW

**Comment by askerlee** [comment]
Thanks for the improvement. It helps me on my small code.

**Comment by MartinThoma** [comment]
Hey! I know it's now 4 years since you've opened the PR - but finally I'm looking over it :sweat_smile: 

Would you mind to fix the merge conflicts?

If you don't want to do it, I can take care of it; giving credit to you via the co-authored-by feature of GitHub.

**Comment by sylvainpelissier** [comment]
Hi, I think it is ok now.

**Comment by sylvainpelissier** [comment]
Is it ok to merge ?

**Comment by MartinThoma** [comment]
I'm sorry, I missed your comments :disappointed: 

The scripts are now in another project: https://github.com/py-pdf/cpdf
They work with Python 3, but I'm uncertain if the color space changes are in there. Feel free to open a PR there :-)

**Pull request closed without merging**
