### PR TITLE
Advanced text extraction

### PR DESCRIPTION
**Pull request by asabramo**
The work on this branch takes text extraction to much more advanced levels.
It mainly includes support for:
* Unicode CMAPs (/ToUnicode and /Differences)
* Correct line extraction
* Extract text widths
* Properly handle nested objects
* Specific support for the Hebrew language encoding is added. Testing was done on both Hebrew and English documents

These are many changes that I've worked on for a while, I did my best to clean up and order them in the limited time I have to do it.
Note - this is my first time contributing to projects on Github so please let me know if I need to do anything differently.

### CODE REVIEW

**Comment by dkreiser** [comment]
I was not able to get this working. Seems like you have mixed python 2 and 3 somehow?

**Comment by asabramo** [comment]
Hm... I don't know what it means to mix the two but I was using only Python
2 in my work.
So it is quite likely that Python 3 would be broken one way or another
because I haven't tested it.
Any specific places that you can point at?

**Comment by asabramo** [comment]
Hi,
I have uploaded a fix that at least makes the unit tests pass:
python2 -m unittest Tests.tests && python3 -m unittest Tests.tests
....
----------------------------------------------------------------------
Ran 4 tests in 0.074s

OK
....
----------------------------------------------------------------------
Ran 4 tests in 0.069s

OK


Assi

**Comment by dkreiser** [comment]
I appreciate you looking into this so quickly. The project documentation says PyPDF2 is fully compatible with specific versions of Python 2 and 3. I am working with Python 3.5.

This PR looks promising for my situation, as I've recently run into some limitations in PyPDF's ability to extract text from newer PDF files with a character map. Specifically, they were generated with the latest version of Crystal Reports for .NET. 

Currently I get this error when I call the extractText() method:

  File "PythonTestScript.py", line 199, in <module>
    text = inputPDF.getPage(p).extractText()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 2868, in extractText
    return self.extractTextState(lineCallback=lineCallback, lineMargin=lineMargin).text
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 3096, in extractTextState
    processOperations(content, self)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 3002, in processOperations
    dbg(2, operator + ": x = " + repr(newX) + " y = " + repr(newY) + "xMult = " + repr(operands[3]))
TypeError: can't concat str to bytes

**Comment by asabramo** [comment]
Hi,
I just uploaded more fixes of the same kind, and tested with more PDF files, hopefully this solves the issue for all files.
Assi

**Comment by dkreiser** [comment]
Hey there -

Thanks for looking into this. It looks like your latest changes fixed the issues I was having with regards to text extraction, which is very exciting!

I did run into one additional issue now with writing PDFs that I wasn't getting with the base version of PyPDF2. In my Python script, I have the lines below within a for-loop to write multiple PDFs from my original PDF:

for r in reports:
    output = PdfFileWriter()
    with open(testPath + "/" +  r["Filename"], "wb") as outputStream:
                    output.write(outputStream)

With your version of the library, those lines of code work for the first iteration of the loop, but not for any successive iterations. In other words, I do get one correct PDF out of my script, but not the others. Here is the exception that is thrown:

Traceback (most recent call last):
  File "PythonTestScript.py", line 530, in <module>
    output.write(outputStream)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 655, in write
    self._sweepIndirectReferences(externalReferenceMap, self._root)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 745, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 721, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 745, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 721, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 730, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, data[i])
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 745, in _sweepIndirectReferences
    self._sweepIndirectReferences(externMap, realdata)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 721, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 762, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 721, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 721, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 762, in _sweepIndirectReferences
    newobj = self._sweepIndirectReferences(externMap, newobj)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 721, in _sweepIndirectReferences
    value = self._sweepIndirectReferences(externMap, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\PyPDF2\pdf.py", line 748, in _sweepIndirectReferences
    if data.pdf.stream.closed:
AttributeError: 'PdfFileWriter' object has no attribute 'stream'

**Comment by asabramo** [comment]
Hi David,
Just wanted to update that I do see this issue as well - I added a small test that mimics your use case (using "thecrasyonez.pdf") and the test passes for N=1 and fails for N>1 with the same error. This happens on both Python2 and Python3 (although this test exposed an issue in Python2 which I had to fix and I still haven't uploaded).

Right now I have no idea where this is coming from...
When I look at it with the debugger at the time of the crash, the data object indeed doesn't have a pdf attribute. I don't know this part of the code and I don't have much time to debug it, and I don't understand how it's related to any changes that I made. So if anybody has time and motivation to look at this, please do.

elif isinstance(data, IndirectObject):
            # internal indirect references are fine
            if data.pdf == self:
                if data.idnum in self.stack:
                    return data
                else:
                    self.stack.append(data.idnum)
                    realdata = self.getObject(data)
                    self._sweepIndirectReferences(externMap, realdata)
                    return data
            else:
                if data.pdf.stream.closed: <-- THIS IS WHERE IT CRASHES
                    raise ValueError("I/O operation on closed file: {}".format(data.pdf.stream.name))
                newobj = externMap.get(data.pdf, {}).get(data.generation, {}).get(data.idnum, None)
        
Assi

**Comment by dkreiser** [comment]
I don't have much knowledge of the inner-workings of this library, but playing with the debugger I think this is a bug with the original library which for some reason is just now being uncovered due to your changes.

There is indeed no stream attribute on data.pdf within the _sweepIndirectReferences function, even on the first iteration of the loop when it writes a PDF correctly. The condition "if data.pdf.stream.closed:" is not a valid way of checking if the stream is closed in that context.

I was not sure how one could get access to the stream attribute in this context (if there is even a way), but I knew my stream was open so I just commented out that condition (lines 748/749). This actually worked for me and my program produced all the PDF files I needed correctly. I can't speak as to whether this breaks other functionality in the library, but I think it is sufficient for my purposes so I am going to make that change locally and roll with it. 

Thanks for your work on this.

**Comment by Tom-Evers** [comment]
So... I upgraded the extractText() function in #397 
Does this conflict with those changes?

**Comment by asabramo** [comment]
Hi,
I haven't tried to merge these branches so I can't say for sure what level
of conflict exists, but it does look like the changes address similar areas
of the code and similar issues.
Your changes are far simpler and I expect my changes are more generic. I'm
not sure if your change is needed if my code is present, but it's very much
possible that your code does address different corner cases.
If you have time to try my branch on your example PDFs, that would be the
simplest way to find out.
Sorry for not having the time to check these things deeper.
Assi

**Comment by MartinThoma** [comment]
I like this a lot! I need more time to get into the library / improve tests coverage, but I'm definitely in favor of improving the text extraction!

**Comment by MartinThoma** [comment]
Is it ok if I resolve the issues?

**Comment by asabramo** [comment]
Hi Martin,
I'm happy to see you found this work useful.
I'm not sure if by "resolve " you mean mark as resolved, or actually push
fixes for them...
I'm not working on this project at all nowadays, so if you find anything
you can improve, you are more than welcome.
Personally I won't have the time to review or test, so I trust your
judgement.
Cheers,
Assi

**Comment by MartinThoma** [comment]
Cool, I understand that. Thank you for the swift answer and the pr! I'll take care of the rest :-)

**Comment by MartinThoma** [comment]
@pubpub-zz The file `glyphNamesToUnicode.py` seems to be pretty similar to `_adobe_glyphs.py`. The differences are:

* `_adobe_glyphs.adobe_glyphs` vs `glyphNamesToUnicode.glyphNamesToUnicode`
* `_adobe_glyphs` creates the dictionary in one run, whereas `glyphNamesToUnicode` creates an empty dictionary first and adds the items. I think creating it in one run might be better:
* `"/parenleft": "\u0028",` vs `glyphNamesToUnicode['parenleft'] = 0x0028` -- note the missing leading backslash and the hex representation vs the unicode symbol representation. I think it's better what we have right now as we can use it directly.
* :warning: `_adobe_glyphs` has roughly 4,320 symbols whereas `glyphNamesToUnicode` has roughly 14,680 symbols. I wonder if we need the additional 10,000 symbols.

**Comment by MartinThoma** [comment]
@asabramo We (well, @pubpub-zz deserves all of the credit :smile: ) worked a lot on improving the text extraction capabilities of PyPDF2. I think this PR is no longer necessary.

I'm sorry it took so long. Thank you very much for putting the effort in writing this PR :hugs:

**Pull request closed without merging**
