### PR TITLE
BUG: Fix issues with non-ascii but also non-utf-8 NameObjects

### PR DESCRIPTION
**Pull request by vashek**
If not strict, readFromStream was returning a NameObject with undecoded bytes when the name fails UTF-8 decoding. This makes sure it's always a string, falling back to latin-1 decoding (which may not always be ideal, but at least it never fails).

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you for your contribution!

I'd be interested in other peoples opinion on the latin-1 fix.

**Comment by vashek** [comment]
To explain further: in Python 2, this was presumably never an issue because bytes and strings were the same. In Python 3 though, sometimes (arguably, only with non-standard PDFs), the NameObject is bytes instead of str, which then requires workarounds in code that uses them. This makes sure that NameObject is indeed always a str.
Also, latin-1 encoding has the special property of being a 1:1 mapping of all 256 bytes to a corresponding character of the same ordinal value, so the decoding of any sequence of bytes never fails and is never ambiguous.

**Comment by MartinThoma** [comment]
The unicode issues is why I want to drop Python 2.7 as soon as possible :see_no_evil:

**Comment by vashek** [comment]
Argh, sorry, I thought I remembered how Python 2 worked but it's been too long.
Turns out, I guess this can't ever have worked properly in Py2 for non-ASCII names??? Because NameObject inherits from str and not from unicode, so even if the name is successfully decoded from utf-8, making a NameObject out of it fails.
We can't change NameObject to inherit from unicode as that would break old code. So I'd say that in Py2, we shouldn't attempt to decode the name at all and instead just keep it as the raw bytes we read from the PDF stream.

**Comment by MartinThoma** [comment]
Do you happen to have a PDF that was not working before but does work with this PR?

**Comment by MartinThoma** [comment]
@pubpub-zz What do you think about this change? Has Latin-1 any special role in the PDF format?

**Comment by MartinThoma** [comment]
This PR is just a variant of https://github.com/py-pdf/PyPDF2/pull/367. As #367 existed years before, I'll close #680 and continue the discussion there.

**Pull request closed without merging**
