### PR TITLE
ROB : improve nameobject reading/writing

### LINKED ISSUE #1344: PDF Read/Merge generates broken documents since update 2.10.6
Hello,

Since update 2.10.6, some PDF documents are not merged correctly. Same with version 2.10.7.
Previous versions (2.10.5 and below) behave correctly.

## Environment

Which environment were you using when you encountered the problem?

```bash
$ python -m platform
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-Ubuntu-20.04-focal
Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-debian-11.2

$ python3 -c "import PyPDF2;print(PyPDF2.__version__)"
2.10.6
```

## Code + PDF

This is a minimal, complete example that shows the issue:

```python
# requirements.txt
diff-pdf-visually==1.7.0
PyPDF2==2.10.6
pytest==7.1.3
```

```python
# test_same_pdf.py
import io
import shutil
import tempfile
from PyPDF2 import PdfMerger, PdfReader
from diff_pdf_visually import pdf_similar
import os
import pytest
import logging


logger = logging.getLogger(__name__)

FILE_INPUT_URI = "arret_maladie.pdf"
FILE_OUTPUT_URI = "output.pdf"


def file_as_bytesio(filepath: str):
    """Open a file as BytesIO, read only."""
    with open(filepath, "rb") as f:
        return io.BytesIO(f.read())


def test_pdf_merger():

    # Open document and merge it into a temporary file
    merger = PdfMerger()

    merger.append(PdfReader(file_as_bytesio(FILE_INPUT_URI)))

    # Write the final merged document
    temp_file = tempfile.NamedTemporaryFile()
    merger.write(temp_file.name)

    temp_file_path = temp_file.name

    # Compare VISUALLY the content of the newly generated file with the expected content
    if not pdf_similar(temp_file_path, FILE_INPUT_URI):
        # If files don't match visually, the test fails.
        # Copy the newly generated file to the current directory to manually check what is wrong
        current_dir = os.path.dirname(__file__)
        new_file_path = os.path.join(current_dir, FILE_OUTPUT_URI)
        shutil.copy2(temp_file.name, new_file_path)
        logger.error(f"The newly merged file does not match with the intput file.")
        # Fail the test on purpose
        assert False

```

Here is the PDF that caused the issue:
[input.pdf](https://github.com/py-pdf/PyPDF2/files/9549001/input.pdf)

Here is the output (simple PdfReader -> PdfMerger):
[output.pdf](https://github.com/py-pdf/PyPDF2/files/9549012/output.pdf)

## Traceback

This is the complete Traceback I see:

```log
Converting each page of the PDFs to an image...
  PDFs have same number of pages. Checking each pair of converted images...
Min sig = 13.4442, significant?=True. The PDFs are different. The most different pages are: page 1 (sgf. 13.4442), page 2 (sgf. 13.6684), page 3 (sgf. 13.9239).
ERROR    test_same_pdf:test_same_pdf.py:44 The newly merged file does not match with the intput file.
```

Thank you for taking the time to investigate.
The document is a French official form, I guess it's fine for using it in automated tests, but not sure.

### PR DESCRIPTION
**Pull request by pubpub-zz**
closes #1344

### CODE REVIEW

**Comment by pubpub-zz** [comment]
Ready for review and testing . I will add later some comments about changes

**Comment by Merinorus** [comment]
Unfortunately, it doesn't seem to pass CI, but the issue #1344 is fixed with this PR

**Comment by pubpub-zz** [comment]
more details on mod:
a) _cmap.py : the str is coming from "/Encoding" which stores a NameObject : the conversion is already performed no need to force it.
b) _page.py : Obsolete called missed in _debug_for_extract()
c) _base.py:
**unnumber** : all #xx should be performed prior to conversion to str (using utf-8) to allow multi language text:
image
**read_from_stream** : if utf-8 (normally the only one required) or gbk (kept to prevent regression) we will use charmap to get some sequence of chars
**renumber** : added to recode  in #xx sequence : 
image
renumber will also be compatible with utf-8 chars

else test added (some test were not iaw pdf spec and have been corrected)
a test using the pdf from the issue has been added in test_merger

**Comment by MartinThoma** [comment]
Thank you @pubpub-zz :pray: 

I will make a release to PyPI in a few minutes.

**Pull request merged**
