### PR TITLE
Add Scripts/booklet.py.

### PR DESCRIPTION
**Pull request by avm**
A script to create centerfold brochures/booklets, similar to bookletcreator.com.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you for the contribution!

I'm uncertain if such script should be part of this repository. Adding it would mean we need to maintain it. It's not shipped with PyPDF2 (the PyPI package) anyway, hence I tend to not have the scripts here at all.

Maybe having a `PyPDF2-contributions` repository or similar would make sense?

**Comment by avm** [comment]
Whatever suits you best. I saw Scripts/2-up.py in the repo and thought that maybe booklet.py belongs there too, but I guess I can keep it to myself :-).

**Comment by MartinThoma** [comment]
I've just became a maintainer yesterday, so give me a bit of time to organize stuff :-) I'll come back :crossed_fingers:

**Comment by MartinThoma** [comment]
Thank you for your contribution!

**Pull request merged**
