### PR TITLE
Fix some conversion errors on non conform PDF

### PR DESCRIPTION
**Pull request by pubpub-zz**
tracked in #925

Iss due to an error in the stream pointing onto \n before the object

fix: move to next non whitespace

### CODE REVIEW

**Comment by MartinThoma** [comment]
@pubpub-zz Just a short heads-up: The reason why I didn't merge so far is copyright concerns. I have contacted the email mentioned in the PDF and asked for permission to add it to PyPDF2. If that permission is not given, we cannot add it.

Without the permission, I see two ways to merge the PR:

1. Removing the PDF (and the test, sadly)
2. Removing the PDF, but adding the PDF download within the test (instead of relying on the PDF being in the repo)

**Comment by MartinThoma** [comment]
I fear that we will not get an answer and thus we will not be able to add this PDF.

@pubpub-zz I've tred to craft a PDF with that specific problem, but I failed. This is what I had:

```
    pdf_data = (
        b"%%PDF-1.7\n"
        b"1 0 obj << /Count 1 /Kids [4 0 R] /Type /Pages >> endobj\n"
        b"2 0 obj << >> endobj\n"
        b"3 0 obj << >> endobj\n"
        b"4 0 obj << /Contents 3 0 R /CropBox [0.0 0.0 2550.0 3508.0]"
        b" /MediaBox [0.0 0.0 2550.0 3508.0] /Parent 1 0 R"
        b" /Resources << /Font << >> >>"
        b" /Rotate 0 /Type /Page >> endobj\n"
        b"5 0 obj << /Pages 1 0 R /Type /Catalog >> endobj\n"
        b"xref 1 5\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"%010d 00000 n\n"
        b"trailer << /Root 5 0 R /Size 6 >>\n"
        b"startxref\n%d\n"
        b"%%%%EOF"
    )
    startx_correction = -1
    pdf_data = pdf_data % (
        pdf_data.find(b"1 0 obj") + startx_correction,
        pdf_data.find(b"2 0 obj") + startx_correction,
        pdf_data.find(b"3 0 obj") + startx_correction,
        pdf_data.find(b"4 0 obj") + startx_correction,
        pdf_data.find(b"5 0 obj") + startx_correction,
        # startx_correction should be -1 due to double % at the beginning indiducing an error on startxref computation
        pdf_data.find(b"xref") + startx_correction,
    )
    pdf_stream = io.BytesIO(pdf_data)
    reader = PdfReader(pdf_stream)
```

**Comment by pubpub-zz** [comment]
This is more tricky to reproduce:  the fix deals with Objects stream. we can produce like that. :(
I've started to try to use pdftk but I think it will be difficult too...
we should focus on option 2...

**Comment by pubpub-zz** [comment]
@MartinThoma, ready for merging 😉

**Comment by MartinThoma** [comment]
@pubpub-zz Could you please run `git rm resources/iss_925.pdf`? The file is still in the PR and I cannot remove it without creating a new PR.

**Pull request merged**
