### PR TITLE
Remove NUL bytes at the end of UTF-16 strings

### PR DESCRIPTION
**Pull request by magcius**
Sometimes, I've noticed trailing NULs at the end of UTF-16 strings in
PDFs in the wild. Strip these out if we find them.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Do those NUL bytes cause issues? Could you provide a unit test that shows the issue?

**Comment by MartinThoma** [comment]
Sorry that it took 6 years :sweat_smile:

**Comment by MartinThoma** [comment]
@pubpub-zz What do you think about this PR?

**Comment by pubpub-zz** [comment]
A lot of rework has been done about this through text extraction. not sure this is still required. @magcius, can you send an example of such a file to confirm this.

**Comment by MartinThoma** [comment]
@pubpub-zz I doubt we will get an answer as I have asked a question over 2 months ago (and he opened the PR more than 6 years ago).

For this reason, I'll close the PR. If we get a response, I can still open it again. Thanks for having a look :-)

**Comment by magcius** [comment]
Yeah, I haven't been employed at the place that needed this fix for well over 6 years now, and the product we needed it on was discontinued. Apologies for not closing it out sooner -- I must have missed the earlier notification.

**Pull request closed without merging**
