### PR TITLE
Make selenium-generated PDF readable

### LINKED ISSUE #177: PdfReadError: EOF marker not found error when opening pdf files generated from selenium snapshot
I am using selenium and Ghost to capture screenshots as `pdf`. The code for saving screenshot is

```
driver.get('http://localhost/report/10?page=1')
driver.save_screenshot('page1.pdf')
```

Now i can open these files in a pdf viewer(I am using Okular) and they look fine. But when i try to open them using this code

```
from PyPDF2 import PdfFileReader
input1 = PdfFileReader(open("page1.pdf", "rb"))
```

It gives error `PdfReadError: EOF marker not found`. The reason i am trying to open this file using `PdfFileReader` is that i need to merge several pdfs into one and for that i need to open these pdfs. I found a github issue https://github.com/mstamy2/PyPDF2/issues/34 and it says it was resolved but i still face this issue. My pypdf version is 1.24

### PR DESCRIPTION
**Pull request by akolpakov**
Try to find “%%EOF” in last 1Mb of file.
In some PDF files, “%%EOF” sign can be far away from the end of document

### CODE REVIEW

**Comment by brettlangdon** [comment]
@akolpakov thank you! This fixed the problem I was having.

**Comment by togakangaroo** [comment]
Can this get merged? I'm seeing this right now in the most recent pip release

**Comment by B-Stefan** [comment]
Please merge this PR. We ran into the same issue.

**Comment by reportgunner** [comment]
thank you @akolpakov !

**Comment by mccorkle** [comment]
Maybe this will help someone else -- but I ran into this issue when an xls file was included in my PDF list of files.  After removing that xls file from the group to be merged, the issue no longer happens in my environment.  Check all your

**Comment by MartinThoma** [comment]
@markdoliner Thank you for the summary!

**Comment by MartinThoma** [comment]
Does anybody have a small PDF created by selenium that has this issue? I would like to add it to the test suite.

**Comment by markdoliner** [comment]
Hi, @MartinThoma. Sorry I don't think I can share the PDF where I saw this problem since it contains private information :-(

**Comment by MartinThoma** [comment]
Are you maybe able to generate a minimal example with another website? If all selenium-generated PDFs are affected, this should be rather easy. You could https://pypi.org/project/PyPDF2/

**Comment by guillaume-uH57J9** [comment]
I added a comment there with a link to a test PDF, and instruction to generate this kind of test PDF.
https://github.com/py-pdf/PyPDF2/issues/177#issuecomment-1099544674

**Pull request merged**
