### PR TITLE
BUG: Fix `updatePageFormFieldValues` when pdf has more than one field with the same name

### PR DESCRIPTION
**Pull request by bangbao**
If the PDF file has more than one field with the same name, the `writer_annot` object will not have the '/T' attribute, then it will not be filled. So, fix it.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Hey! I know it's now 3 years, but do you maybe have such an example PDF which we could use for testing?

**Comment by MartinThoma** [comment]
I think the gist of this PR was already merged in another PR:

```
        # Iterate through pages, update field values
        for j in range(0, len(page[PG.ANNOTS])):
            writer_annot = page[PG.ANNOTS][j].getObject()
            # retrieve parent field values, if present
            writer_parent_annot = {}  # fallback if it's not there
            if PG.PARENT in writer_annot:
                writer_parent_annot = writer_annot[PG.PARENT]
            for field in fields:
                if writer_annot.get('/T') == field:
                    writer_annot.update({
                        NameObject("/V"): TextStringObject(fields[field])
                    })
                elif writer_parent_annot.get('/T') == field:
                    writer_parent_annot.update({
                        NameObject("/V"): TextStringObject(fields[field])
                    })
```

**Comment by MartinThoma** [comment]
Seems no longer necessary

**Comment by bangbao** [comment]
ok

**Pull request closed without merging**
