### PR TITLE
BUG: Undefined indirect objects

### PR DESCRIPTION
**Pull request by jvalenzuela**
Correctly, or so I hope, return null objects when dereferencing undefined indirect objects.

### CODE REVIEW

**Comment by vrocha** [comment]
Please merge this or at least https://github.com/mstamy2/PyPDF2/pull/411

**Comment by jvalenzuela** [comment]
Merged.

**Comment by MartinThoma** [comment]
Is this related to any issue?

**Comment by MartinThoma** [comment]
I am uncertain why this change was proposed and if it is still necessary. I will close this PR now. I'm open to review it again if anybody has more information.

**Pull request closed without merging**
