### PR TITLE
MAINT: Use typing.IO for file streams

### PR DESCRIPTION
**Pull request by thehale**
The Python standard library provides the `IO` type for file streams. [[source](https://docs.python.org/3/library/typing.html#typing.IO)]

This commit replaces the complex Union type of the various IO implementations with the official `IO` type. This will improve the accuracy of type checking in users' IDEs.

-------

There are also a few quality-of-life improvements for new code contributors like myself.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you for the contribution!

This time it might take a little bit longer until the release happens as I want to make the 3.0.0 release :-)

**Comment by MartinThoma** [comment]
If you want, I'll add you to the list of contributors: [contributors — PyPDF2 documentation](https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html)

**Comment by thehale** [comment]
> If you want, I'll add you to the list of contributors: [contributors — PyPDF2 documentation](https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html)

Go for it. :D Thanks!

**Comment by MartinThoma** [comment]
Done :hugs:

**Pull request merged**
