### PR TITLE
BUG: fix Named object encoding error

### PR DESCRIPTION
**Pull request by exiledkingcc**
Named object should be with text_type not binary text

I used PdfFileWriter to convert pdf pages to images, here is the code:

```python
from PyPDF2 import PdfWriter
import io

writer = PdfWriter()
writer.add_page(pdf_obj.pages[0])

data = io.BytesIO()
writer.write(data)
data.seek(0)

with wand.image.Image(file=data, resolution=72, background=wand.color.Color("white")) as img:
       data = img.make_blob("png")
...
```
but the image is wrong, the `wand` library can't deal with the pdf which created by `PdfFileWriter` :
```
   **** File has an unbalanced >> (close dictionary).
   **** Warning: obj definition followed by multiple tokens, attempting to recover.
......
......
   **** This file had errors that were repaired or ignored.
   **** The file was produced by: 
   **** >>>> PyPDF2 <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.
```
wrong image:
wrong

right image:
right

this fix the problem.

### CODE REVIEW

**Comment by exiledkingcc** [comment]
it' caused by a pdf created by `Microsoft® Word 2010`.
the pdf has font name `b'/ABCDEE+\xcb\xce\xcc\xe5'`, which can't be decoded by utf-8

**Comment by JackieFei** [comment]
This font name is GB2312 encoding :
\xcb\xce = 宋
\xcc\xe5 = 体

**Comment by exiledkingcc** [comment]
@JackieFei 
yes. it should be decoded with the right encoding,
but which is the RIGHT encoding?  is it recorded in the pdf?

**Comment by MartinThoma** [comment]
@JackieFei how do you know that Latin1 is always the right encoding?

**Pull request closed without merging**
