### PR TITLE
fix pdf reader getting stuck on large files without startxref marker

### PR DESCRIPTION
**Pull request by dsk7**

### CODE REVIEW

**Comment by dsk7** [comment]
Hi! We found a bug where PyPDF got stuck on a certain kind of broken files.
This pull request adds a test and fixes the bug.

Happy coding
dsk7

**Comment by vstoykov** [comment]
The test is not Python3 compatible. In Python 3 there is no StringIO package.

**Comment by MartinThoma** [comment]
@dsk7 Thank you for your PR - sorry that it took so long. 

Would you mind to resolve the merge conflicts?

**Comment by dsk7** [comment]
I'll have a look at it!

**Comment by dsk7** [comment]
I had a look: The solution suggested here is not compatible with the changes made in the mean time. I'll open a new pull request following a different (and much better) route.

**Comment by MartinThoma** [comment]
Replaced by https://github.com/py-pdf/PyPDF2/pull/808 and that one was merged :tada:  - the release will be in April (some time in the next few days)

**Pull request closed without merging**
