### PR TITLE
WIP: support font CMAP to translate chars with TJ operator

### PR DESCRIPTION
**Pull request by VictorCarlquist**
Hello!

With this PR is possible to extractText from TJ operator, fixing the issues #576 and #654

It's adding support to CMAP translate when the PDF uses ToUnicode.

I need to add some tests on it yet.

Edit:
---
the issue #654 isn't fixed, I tested with the first link described in that issue, but the second link isn't returning text. I'm debug it, seems that the cmap table contains chars and bytes, if we convert the entire table to byte it will work.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Very nice! I'm looking forward to this one!

**Comment by MartinThoma** [comment]
By the way: it might make more sense to point this pr to the 2.0.0-dev branch. I'll only add Bugfixes to the 1.x version. I hope to finish the move to 2.x this month.

**Comment by VictorCarlquist** [comment]
Ok, nice! I was struggling with python2.7...

I'll change the code to support only python3.

**Comment by MartinThoma** [comment]
@VictorCarlquist I appreciate your energy :smile: :+1: But please be aware that it will take the rest of May to clean things up. You will get a lot of merge conflicts if you start working on this now.

**Comment by VictorCarlquist** [comment]
This PR seems to do almost the same thing of the #881. @pubpub-zz and  @MartinThoma you can confirm it. If so, we can close this PR.

**Comment by MartinThoma** [comment]
I ran [the benchmark](https://github.com/py-pdf/benchmarks) which I also ran over [pubpub-zz's pr](https://github.com/py-pdf/PyPDF2/pull/929#issuecomment-1141418912).

I gave a 👍 where your current PR performs better:

```
https://arxiv.org/pdf/1601.03642 : 0.9438654353562005 -> 0.94
https://arxiv.org/pdf/1602.06541 : 0.8978933061501869 -> 0.90
https://arxiv.org/pdf/1707.09725 : 0.9100581720093184 -> 0.91
https://arxiv.org/pdf/2201.00021 : 0.9499215589133845 -> 0.92 <--- drop
https://arxiv.org/pdf/2201.00022 : 0.9102201679631884 -> 0.91
https://arxiv.org/pdf/2201.00029 : 0.0,
https://arxiv.org/pdf/2201.00037 : 0.9155486607869612 -> 0.92
https://arxiv.org/pdf/2201.00069 : 0.8980679211032767 -> 0.29 <---- crazy drop
https://arxiv.org/pdf/2201.00151 : 0.8859883219294902 -> 0.93 👍
https://arxiv.org/pdf/2201.00178 : 0.8927337030785306 -> 0.90
https://arxiv.org/pdf/2201.00200 : 0.9683510183687691 -> 0.94 <-- drop
https://arxiv.org/pdf/2201.00201 : 0.9747879942829919 -> 0.94 <- drop
https://arxiv.org/pdf/2201.00214 : 0.8850769765492426 -> 0.95 <--- huge improvement!
https://arxiv.org/pdf/GeoTopo-book : 0.7860457992901709 -> 0.78
```

**Comment by MartinThoma** [comment]
The results are mixed. In some cases your PR leads to better results, in some cases https://github.com/py-pdf/PyPDF2/pull/929#issuecomment-1141418912 is better. I wouldn't close either for the moment.

I would rather merge #929 as the overall results look better. But I hope that we can combine the best of both PRs.

**Comment by MartinThoma** [comment]
@VictorCarlquist I've merged #924 and just restructured the code a bit. I think that the current `main` branch contains everything that was added with this PR (and some more things).

Do you want to check?

If you don't want to have a look, I would close this PR. I'll give you credit in the CHANGELOG for the next release for working on this feature.

**Comment by MartinThoma** [comment]
You mentioned that this PR is fixing the issues https://github.com/py-pdf/PyPDF2/issues/576 and https://github.com/py-pdf/PyPDF2/issues/654 .

At least #576 is still an issue with the current `main` branch. Hence I'll leave this PR open.

**Comment by VictorCarlquist** [comment]
> @VictorCarlquist I've merged #924 and just restructured the code a bit. I think that the current `main` branch contains everything that was added with this PR (and some more things).
> 
> Do you want to check?
> 
> If you don't want to have a look, I would close this PR. I'll give you credit in the CHANGELOG for the next release for working on this feature.

> At least #576 is still an issue with the current `main` branch. Hence I'll leave this PR open.

Thank you, I've test the case of #576, this PR  doesn't fix that because the warning is still showing up. but it avoids that program to stop the text extract. The #924 has the same behavior, by the way, very good code.

We can close this PR.

Thanks!

**Comment by MartinThoma** [comment]
Thank you for checking!

**Comment by pubpub-zz** [comment]
I will have a look to see to confirm it will match the corrections I'm working on

**Pull request closed without merging**
