### PR TITLE
DEP: Class, variable, and module names

### PR DESCRIPTION
**Pull request by MartinThoma**
Deprecation Announcements: The following will be deprecated with PyPDF2 2.0.0:

* Python 3.5 and older
* formatWarning : No deprecation warning was added as this leads to a recursion error
* PdfFileReader: The arguments `warndest` and `overwriteWarnings` will be removed. The new default behavior is `overwriteWarnings=False` and `warndest=None`
* PdfFileMerger: The argument `overwriteWarnings` will be removed. The new default behavior is `overwriteWarnings=False`.
* `PyPDF2.merger.OutlinesObject` will be removed without replacement.
* `PyPDF2.pdf`: The `pdf` module will be removed. Import directly from `PyPDF2` instead.
* `PyPDF2.utils`: The `utils` module will become private.

## Core class renames

* PdfFileReader➔ PdfReader
* PdfFileWriter➔ PdfWriter
* PdfFileMerger➔ PdfMerger

### CODE REVIEW

**Comment by MartinThoma** [comment]
This is a preparation for https://github.com/py-pdf/PyPDF2/pull/859

**Comment by pubpub-zz** [comment]
@MartinThoma, May I ask you a question : I do agree that the new names may be more appropriate and in accordance with snake case style, but what not leave the old style with the warning in the future :  there will no drawbacks for PyPDF2 development keeping them to keep backward compatibility with the warning and a very limited support

**Comment by MartinThoma** [comment]
> [why] not leave the old style with the warning in the future : there will no drawbacks for PyPDF2 development keeping them to keep backward compatibility with the warning and a very limited support

I'm currently wondering if I really want to do this style change at all :smile: There are so many tiny places ... that is way more work than I expected (mainly due to the fact that I need to add the deprecation warnings).

Yes, I was also thinking to keep the parts with the warnings for a while - not measured in PyPDF2 versions, but in calendar time. For example, for a year after the 2.0.0 version is on PyPI.

However, I did have a look at a a lot of [StackOverflow questions tagged with PyPDF2](https://stackoverflow.com/questions/tagged/pypdf2). Most people seem to use only very basic features of PyPDF2 and not go into more "internal" topics. The most common use-cases seem to be: (1) Text Extraction (2) simple merges without transformations (3) extracting images (4) getting the number of pages of a document. Hence I would not expect too many hickups / breaking things a lot. But there might be a lot hidden that I'm not aware of.

I want to drop the deprecation warnings eventually as this clutters the code-base, but I also don't want to break existing code. I'm 90% decided by now that I keep the old names for ~1 year after the 2.0.0 release.

What do you think about this idea?

**Comment by MartinThoma** [comment]
@pubpub-zz Looking at `utils.py`, it seems as if all of those functions are probably not used by PyPDF2 users (only by PyPDF2 developers). Hence I think about making the module private (`utils.py` -> `_utils.py`). Do you also think so.

**Comment by pubpub-zz** [comment]
> I'm currently wondering if I really want to do this style change at all 😄 There are so many tiny places ... that is way more work than I expected (mainly due to the fact that I need to add the deprecation warnings).


I've started this work previously to match pylint and it has been a hudge job not finish. 
I also agree that we should focus(only?) in providing a snake case style API for the documented functions

> want to drop the deprecation warnings eventually as this clutters the code-base, but I also don't want to break existing code. I'm 90% decided by now that I keep the old names for ~1 year after the 2.0.0 release.

What About using @MasterOdin's proposal (https://github.com/py-pdf/PyPDF2/discussions/684#discussioncomment-2535379) to provide both functions names but encoding the snake case style? warning can still be introduced there.

Also I do like your idea to about PendingDeprecationWarning,but I've just discovered that this warning is nearly all the time not reported. perhaps we should use our our warning and provide a function set the warning filters to show/hide them

**Comment by pubpub-zz** [comment]
> @pubpub-zz Looking at `utils.py`, it seems as if all of those functions are probably not used by PyPDF2 users (only by PyPDF2 developers). Hence I think about making the module private (`utils.py` -> `_utils.py`). Do you also think so.

agreed

**Comment by MartinThoma** [comment]
@pubpub-zz Thank you for your quick feedback; I might ping you more often now :sweat_smile: 

Do you think `cacheIndirectObject` and `cacheGetIndirectObject` should be used by PyPDF2 users? I tried to find how people use it ([link](https://github.com/search?l=Python&q=cacheGetIndirectObject&type=Code)), but that seems to be only/mainly people who copied parts of the source code.

**Comment by MartinThoma** [comment]
> What About using @MasterOdin's proposal (https://github.com/py-pdf/PyPDF2/discussions/684#discussioncomment-2535379) to provide both functions names but encoding the snake case style?

I don't understand the question. Isn't that what I'm doing in this PR?

**Comment by MartinThoma** [comment]
> Also I do like your idea to about PendingDeprecationWarning,but I've just discovered that this warning is nearly all the time not reported. perhaps we should use our our warning and provide a function set the warning filters to show/hide them

You mean something like this?

```
class PyPDF2DeprecationWarning(DeprecationWarning):
    pass
```

I haven't seen that before :thinking: 

> provide a function set the warning filters to show/hide them

I don't see how this would solve the issue that people might miss it. If people enable warnings, they are shown. The problem occurs only when people have/leave the warnings disabled.

I'm pretty heavily editing a lot of StackOverflow questions, so I hope that people see/like the new style and more naturally there. The changelog + the major version change should also make it obvious that there might be breaking changes (and for the changes with most potential for issues I will keep it for longer than the 2.0.0 release; I'm still thinking about how to communicate this properly).

**Comment by pubpub-zz** [comment]
> > What About using @MasterOdin's proposal ([#684 (comment)](https://github.com/py-pdf/PyPDF2/discussions/684#discussioncomment-2535379)) to provide both functions names but encoding the snake case style?
> 
> I don't understand the question. Isn't that what I'm doing in this PR?

You seem to recode manually the alternative names for both. The proposal was to do this 'conversion' at the flight and by code.

**Comment by pubpub-zz** [comment]
> > Also I do like your idea to about PendingDeprecationWarning,but I've just discovered that this warning is nearly all the time not reported. perhaps we should use our our warning and provide a function set the warning filters to show/hide them
> 
> You mean something like this?
> 
> ```
> class PyPDF2DeprecationWarning(DeprecationWarning):
>     pass
> ```
> 
> I haven't seen that before 🤔
> 
> > provide a function set the warning filters to show/hide them
> 
> I don't see how this would solve the issue that people might miss it. If people enable warnings, they are shown. The problem occurs only when people have/leave the warnings disabled.
> 
> I'm pretty heavily editing a lot of StackOverflow questions, so I hope that people see/like the new style and more naturally there. The changelog + the major version change should also make it obvious that there might be breaking changes (and for the changes with most potential for issues I will keep it for longer than the 2.0.0 release; I'm still thinking about how to communicate this properly).

I agree my idea is not good.

**Comment by MartinThoma** [comment]
> You seem to recode manually the alternative names for both. The proposal was to do this 'conversion' at the flight and by code.

Yes, I was. How would you do it differently? (I'll read master odins comment again tomorrow to see what I missed :-))

**Comment by MartinThoma** [comment]
TODO for myself: Maybe we can add writer.pages similar to reader.pages?

**Pull request merged**
