### PR TITLE
BUG: Updated pdf fields don't show up when page is written

### LINKED ISSUE #355: Updated pdf fields don't show up when page is written
I'd like to use PyPDF2 to fill out a pdf form. So far, everything is going smoothly, including updating the field text. But when I write the pdf to a file, there is apparently no change in the form. Running this code:

```python
import datetime as dt
from PyPDF2 import PdfFileReader, PdfFileWriter
import re

form701 = PdfFileReader('ABC701LG.pdf')
page = form701.getPage(0)
filled = PdfFileWriter()

#removing extraneous fields
r = re.compile('^[0-9]')
fields = sorted(list(filter(r.match, form701.getFields().keys())), key = lambda x: int(x[0:2]))

filled.addPage(page)
filled.updatePageFormFieldValues(filled.getPage(0), 
                                 {fields[0]: 'some filled in text'})

print(filled.getPage(0)['/Annots'][0].getObject()['/T'])
print(filled.getPage(0)['/Annots'][0].getObject()['/V'])

with open('test.pdf','wb') as fp:
    filled.write(fp)
```
prints text: 

> 1  EFFECTIVE DATE OF THIS SCHEDULE <i.e. the field name>
> some filled in text

But when I open up test.pdf, there is no added text on the page! Help!

### PR DESCRIPTION
**Pull request by mwhit74**
I want to attempt to fix #355 with these modifications.

### CODE REVIEW

**Comment by mwhit74** [comment]
This will also apply to #300.

**Comment by shurshilov** [comment]
[output.pdf](https://github.com/mstamy2/PyPDF2/files/1889795/output.pdf)
Does not work in the fields in this file, for example, the first field for the phone, the second one for some reason works and a few more fields, so the fix is ​​not working

**Comment by mwhit74** [comment]
Please provide more information. What did you try? What is the simplest bit of code you can run that doesn't work?

**Comment by shurshilov** [comment]
For example i try set value to this field (777777) but it dont show.text = input_pdf.getFormTextFields()text['RecipientPhone_afddf77b-d0dd-4a0b-9172-fb9e2b0f3fff_177d56ab-58e1-4422-826e-a1778aae107a']='777777'output.updatePageFormFieldValues(getpage, text)BUTin the same file but in the other floor everything works and is displayed without an additional clicktext['SenderPhone_afddf77b-d0dd-4a0b-9172-fb9e2b0f3fff_177d56ab-58e1-4422-826e-a1778aae107a']='888888'09.04.2018, 18:25, "Michael" <notifications@github.com>:Please provide more information. What did you try? What is the simplest bit of code you can run that doesn't work?

**Comment by shurshilov** [comment]
I attached the file in the commentary09.04.2018, 19:29, "Артем Шуршилов" <shurshilov.a@yandex.ru>:For example i try set value to this field (777777) but it dont show.text = input_pdf.getFormTextFields()text['RecipientPhone_afddf77b-d0dd-4a0b-9172-fb9e2b0f3fff_177d56ab-58e1-4422-826e-a1778aae107a']='777777'output.updatePageFormFieldValues(getpage, text)BUTin the same file but in the other floor everything works and is displayed without an additional clicktext['SenderPhone_afddf77b-d0dd-4a0b-9172-fb9e2b0f3fff_177d56ab-58e1-4422-826e-a1778aae107a']='888888'09.04.2018, 18:25, "Michael" <notifications@github.com>:Please provide more information. What did you try? What is the simplest bit of code you can run that doesn't work?

**Pull request merged**
