### PR TITLE
Fix IndexError for getPage() of decryped file (Issue #327)

### PR DESCRIPTION
**Pull request by denis-osipov**
Issue #327 
`_flatten()` method change `flattenedPages` to empty list when trying to get page and then test if  file is encrypted and try to decrypt it. If it fails `PdfReadError("file has not been decrypted")` raise and `flattenedPages` not revert to `None`.
This fix allow to get page from `PdfFileReader` object after decryption.

### CODE REVIEW

**Comment by ameybhavsar24** [comment]
This works for me. I hope they merge it soon.

**Comment by MartinThoma** [comment]
I'm sorry that it took so long. I just became a maintainer of this project.

Do you @ameybhavsar24 / @denis-osipov have an example file / code snippet that shows the issue?

**Comment by MartinThoma** [comment]
I don't understand why this changes anything

**Comment by denis-osipov** [comment]
Hi, @MartinThoma 

There is [an encrypted pdf file](https://github.com/mstamy2/PyPDF2/files/8444774/example.pdf) to use in example:

```py
import PyPDF2

pdfFileObj = open('example.pdf', 'rb')
pdfReader = PyPDF2.PdfFileReader(pdfFileObj)

try:
    # Can't get access to content of encrypted file. It's OK.
    print(pdfReader.getPage(0))
except PyPDF2.utils.PdfReadError as error:
    print('Expected error:', error)

# Password is correct:)
pdfReader.decrypt('test')

try:
    # Current behaviour is unexpected (for me): we decrypted file and now should
    # have access to it's content. But we'll get an error here.
    print(pdfReader.getPage(0))
except IndexError as error:
    print('Unexpected error (file is decrypted now):', error)
```

Problem appears because `_flatten()` method sets `self.flattenedPages` before it try to get pages and doesn't set it back to `None` in case of error. This PR just make `_flatten()` to set `self.flattenedPages` to an empty array **after** it successfully got pages.

If there is a better solution or current behaviour is correct, just close the PR, please.

**Comment by MartinThoma** [comment]
@denis-osipov  Thank you for all the time and patience :pray: 

This PR was just merged and will go into the next release (some time this month)

@ameybhavsar24 It's merged :-) It was by far not soon, but as the new maintainer I hope in future such things get resolved quicker.

**Pull request merged**
