### PR TITLE
DOC: Changed 'latest' for 'stable'

### PR DESCRIPTION
**Pull request by olsonperrensen**
(given master branch is further ahead than stable package)

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you very much, I appreciate it :pray: 

If you want to, I can add you to https://pypdf2.readthedocs.io/en/latest/meta/CONTRIBUTORS.html

**Comment by olsonperrensen** [comment]
Sure! Glad to help :)

**Comment by MartinThoma** [comment]
How should I add you?

* olsonperrensen
* Olson Perrensen
* Max Olson Perrensen
* something else?

**Comment by olsonperrensen** [comment]
olsonperrensen

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/PyPDF2/commit/10ab0854c4cb7f2d4b490ff4178fd170f5d0a9e5 done :-)

**Pull request merged**
