### PR TITLE
Prevent deduplication of PageObject

### PR DESCRIPTION
**Pull request by Hatell**
In issue #1102 adobe reader/acrobat doesn't like if same page is referred more than one time

### CODE REVIEW

**Comment by MartinThoma** [comment]
Does this change fix #1102 ?

**Comment by Hatell** [comment]
I haven't yet confirmed that.

**Comment by Hatell** [comment]
I can now confirm this. Seem to be bug in Adobe Acrobat Reader or something like that. I tested this and confirmed that PDF doesn't shown properly Acrobat Reader DC, 2015 Release, Version 2015.007.20033.

This changes fixes #1102.

Can you find anything from PDF definition document regarding this page object usage multiple times.

**Comment by MartinThoma** [comment]
I'm pretty busy today, but I plan to merge + release this pr this weekend. Thank you already for it ❤️

**Pull request merged**
