### PR TITLE
Ensure indirect sweep to handle all objects.

### LINKED ISSUE #1062: PDFs arent merged properly
After upgrading from version 1.28.1 to version 2.4.1 I've faced an issue with merging linked pdfs. 
I've also checked previous versions and problem appears after 2.0.0 version

## Environment

```bash
$ python -m platform
Linux-5.18.5-200.fc36.x86_64-x86_64-with-glibc2.28

$ python -c "import PyPDF2;print(PyPDF2.__version__)"
2.4.1
```

## Code + PDF
PDFs:
[file1.pdf](https://github.com/py-pdf/PyPDF2/files/9045755/file1.pdf)
[file2.pdf](https://github.com/py-pdf/PyPDF2/files/9045758/file2.pdf)
[merged.pdf](https://github.com/py-pdf/PyPDF2/files/9045759/merged.pdf)

```python
merger = PdfMerger(strict=True)
merger.append("file1.pdf")
merger.merge(1, "file2.pdf")
merger.write("merged.pdf")
```

## Traceback
There is no traceback, but after checking merged.pdf content from file2.pdf dosen't exists, but that slide has dimensions from file2.pdf
It looks like dimensions are from file2.pdf, but image comes from first slide of file1.pdf

# Expected behavior
In second slide of merged.pdf we could see slides from file2.pdf

### PR DESCRIPTION
**Pull request by Hatell**
This fixes #1062

### CODE REVIEW

**Comment by MartinThoma** [comment]
You're quick!

I've just made a bugfix-release so that we have time to fix this. No need to rush :-)

**Comment by Hatell** [comment]
Could you run tests for unknown reason they didn't run.

I found that there was missing some cross references added them as well.

**Comment by MartinThoma** [comment]
@Hatell I've just added a tiny stylistic commit. I don't know why CI wasn't triggered before

**Comment by MartinThoma** [comment]
@Hatell The failed test might be actually ok. It checks for file identity - so the file needs to be updated. We need to manually inspect the merged file if it looks ok. Not ideal, but better than no check.

**Comment by Hatell** [comment]
Don't merge yet. There is some issues left.

**Comment by Hatell** [comment]
I found that some data to calculate hash was ignored. Now tests should pass.

**Comment by Hatell** [comment]
Now all issues should be resolved.

Added test because coverage checks and found a bug.

There is a bug in main and this fixes it also. I found from previous PR #207 those files with NoneType errors and checked that xref-table is incorrectly produced.

**Comment by MartinThoma** [comment]
Thank you :heart:

**Comment by MartinThoma** [comment]
I'm running the compression checks again

**Comment by MartinThoma** [comment]
It looks ok for me. @MasterOdin what do you think?

**Comment by MasterOdin** [comment]
I'm still quite concerned that both `extern_map` and `self._idnum_hash` are doing very similar things with regards to trying to remove duplicate indirect objects during the sweep, but can potentially mingle in weird ways, especially since we only use `self._idnum_hash` when `extern_map` has a cache miss, but when it doesn't I'm not sure there's a guarantee that what `extern_map` has cached will be the same as what we'd have for `self._idnum_hash`, and so I guess we could still end up with repeated objects, though less than before.

Can we replace `extern_map` with `self._idnum_hash`?

**Comment by Hatell** [comment]
It may work.

Need only to figure how this `extern_map` which is like tree structure based on pdf, generation and idnum to transform a flat lookup-table.

Also I would change this recursive depth-first processing to iterative version. Maybe after this structure change.

**Pull request closed without merging**
