### PR TITLE
ROB: Padding issue with AES encryption

### LINKED ISSUE #1221: PyCryptoDome padding issue, AES encryption CBC mode
This is not a fully qualified bug report, because I lack a reproducible example for a number of reasons. However, I [originally posted](https://github.com/py-pdf/PyPDF2/issues/416#issuecomment-1162421025) in issue 416 about how I was experiencing decryption issue with a file generated by the Acrobat Sign product. It is a v1.7 PDF, with AES 128-bit encryption. That issue notes a merged fix (#1015).

I downloaded PyPDF2 2.10.0, which then gave a new error about missing PyCryptoDome, which I then installed (v3.15.0). Running my test case again, I received the following error:
```
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

I know little about PDF specs, and even less about encryption, however using the PyCryptoDome docs I did find that the following code addition to `_encryption.py` alleviated this issue for my file:
```
86a87,89
>             if len(data) % 16:
>                 from Crypto.Util.Padding import pad
>                 data = pad(data, 16)
```

Again, lacking a reproducible test case I'm not sure how useful this is but wanted to share my findings in case someone with access to Acrobat Sign can generate a file that demonstrates the same behavior.

### PR DESCRIPTION
**Pull request by MartinThoma**
Fixes #1221

Credit goes to Alper ahmetoglu for the fix

Co-authored-by: Alper Ahmetoglu <ahmetoglu.alper@gmail.com>

### CODE REVIEW

**Comment by MartinThoma** [comment]
@exiledkingcc Does this change make sense to you?

**Comment by pubpub-zz** [comment]
from PDF reference 1.7, §3.5.1:
Strings and streams encrypted with AES use a padding scheme that is described in Internet RFC 2898, PKCS #5: Password-Based Cryptography Specification Version 2.0; see the Bibliography. **For an original message length of M, the pad consists of 16 - (M mod 16) bytes whose value is also 16 - (M mod 16).** For example, a 9-byte message has a pad of 7 bytes, each with the value 0x07. The pad can be unambiguously removed to determine the original message length when decrypting. Note that the pad is present when M is evenly divisible by 16; it contains 16 bytes of 0x10.

it looks good to me. Just surprise it has not been detected earlier : A test would be welcomed

**Comment by pubpub-zz** [comment]
from PDF reference 1.7, §3.5.1:
Strings and streams encrypted with AES use a padding scheme that is described in Internet RFC 2898, PKCS #5: Password-Based Cryptography Specification Version 2.0; see the Bibliography. **For an original message length of M, the pad consists of 16 - (M mod 16) bytes whose value is also 16 - (M mod 16).** For example, a 9-byte message has a pad of 7 bytes, each with the value 0x07. The pad can be unambiguously removed to determine the original message length when decrypting. Note that the pad is present when M is evenly divisible by 16; it contains 16 bytes of 0x10.

it looks good to me. Just surprise it has not been detected earlier : A test would be welcomed

**Comment by exiledkingcc** [comment]
i'think the PDF file maybe corrupted.
when encrypting, the data should be padded, after encryption, the length of result is **always a multiple of 16**.
so, decryption needs NO padding.

**Comment by MartinThoma** [comment]
@exiledkingcc it shouldn't need it, I thought so as well.

But would adding the padding here ever break a non-broken pdf? Maybe it's worth including it for robustness

**Pull request merged**
