### PR TITLE
Custom implementation of warnings.formatwarning removed

### PR DESCRIPTION
**Pull request by pavelbrych**
Custom implementation of formatwarning interfering with other modules removed as stated in #67

### CODE REVIEW

**Comment by uberparkhill** [comment]
Can I ask why this pull request was never merged?  I'm running into same issues with custom formatwarning interference, and it looks like the problem has already been solved, but not committed to master?

**Comment by xmo-odoo** [comment]
@uberparkhill because the project has been essentially unmaintained for a long time, and formally acknowledged as so in 2018 (see  #477)

**Comment by MartinThoma** [comment]
Hey, I'm sorry it's been such a long time. Would you mind to fix the merge conflicts (or open a new PR)?

**Comment by MartinThoma** [comment]
I've added this to https://github.com/py-pdf/PyPDF2/discussions/752 - I definitely want to merge this, but it might break existing users code. Hence only in PyPDF2 2.0

**Comment by MartinThoma** [comment]
This change was incorporated in the PyPDF2 2.0.0 release.

Thank you for your contributing to PyPDF2 🙏

**Pull request closed without merging**
