### PR TITLE
Add support to extract gray scale images

### PR DESCRIPTION
**Pull request by joeywang4**
Currently, when gray scale images are extracted, they will be incorrectly transformed to RGB images. This PR fixed this issue by changing the palette and the mode when images are extracted.

### CODE REVIEW

**Comment by MartinThoma** [comment]
Very nice!

Do you happen to have an example pdf where the new code would be applied? Or could you create one and upload it here?

I would add it to the https://github.com/py-pdf/PyPDF2 + add a test

**Comment by joeywang4** [comment]
Ok, I have uploaded a test file [grayscale.pdf](https://github.com/py-pdf/PyPDF2/blob/62e88e2e375de2a5b1c6906e26d5abd0733c2fb2/resources/grayscale.pdf) and added it to `test_get_images`.

**Comment by MartinThoma** [comment]
Hi @joeywang4 ,

I've just added the `grayscale.pdf` to the `sample-files` git submodule. Would you be so kind to remove the file from your PR + use `sample-files/019-grayscale-image/grayscale-image.pdf`?

I want to avoid that the PyPDF2 repository becomes bigger and bigger due to example PDF files. This might have an impact on people who clone PyPDF2 / install from the repository. Hence adding the file via submodule.

**Review by MartinThoma — CHANGES_REQUESTED** [review]
The code looks good - thanks for adding the test!

Please just remove the `resources/grayscale.pdf` and use `SAMPLE_ROOT / "019-grayscale-image/grayscale-image.pdf"` instead :-)

**Comment by joeywang4** [comment]
@MartinThoma I have removed the test file and updated the path. Thanks for the suggestion!
I also changed the path of the extracted image file when running the test. Otherwise, the extracted image cannot be correctly written to a file when I ran the test locally on my computer.

**Comment by MartinThoma** [comment]
Very good work! 👍

If you want, I'll add you to the contributors list :-)

**Pull request merged**
