### PR TITLE
When merging pages together, clip by trimBox, which would otherwise be ignored

### LINKED ISSUE #163: Question: How to merge cropped PDF page with full pdf page in PyPDF?
I am trying to merge two pdf pages using PyPDF2:

```
background_page = background_pdf.getPage(0)
overlay = some_pdf.getPage(0)

# crop overlaying page vertically
overlay.mediaBox.lowerRight = (
    overlay.mediaBox.getUpperRight_x(),
    overlay.mediaBox.getUpperRight_y() / 2
)
# merge
background_page.mergePage(overlay)
```

Unfortunately cropping doesn't happen. `mediaBox` of the overlaying page appears to be ignored and I see entire page in the output.

Does anyone have any idea of how I can achieve this?

I posted this on SO as well http://stackoverflow.com/questions/27512246/how-to-merge-cropped-pdf-page-with-full-pdf-page-in-pypdf

### PR DESCRIPTION
**Pull request by forrestv**
Fixes #163

### CODE REVIEW

**Comment by MaxLeidlTEXSIB** [comment]
This fix does not work if the trimBox doesn't start at (0, 0). In those cases the code has to look like this:

`page2Content = ContentStream(page2Content, self.pdf)`
`page2Content.operations.insert(0, [map(FloatObject, [page2.trimBox.getLowerLeft_x(), page2.trimBox.getLowerLeft_y(), page2.trimBox.getWidth() - page2.trimBox.getLowerLeft_x(), page2.trimBox.getHeight() - page2.trimBox.getLowerLeft_y()]), "re"])`

Otherwise the clip would be smaller than expected.

**Comment by forrestv** [comment]
Hi @MaxLeidlTEXSIB. I don't think that's correct?

image

At least, that would be pretty surprising... e.g. can you explain why `width = page2.trimBox.getWidth() - page2.trimBox.getLowerLeft_x()` is correct? Maybe there's another bug somewhere that you're compensating for?

**Comment by MaxLeidlTEXSIB** [comment]
After looking into it further, I found out that you are right, it was just compensating for a bug in my code. Since I was working with trimBoxes with their origin != (0, 0), I added a transformation to the pdf, moving it to that point, but I wasn't aware I also had to move the trimBox manually. With this change your code works perfectly, thank you for pointing it out 😄

**Comment by MartinThoma** [comment]
Thank you for the PR and sorry that it took so long - it will be part of the next release (some time this month)

**Pull request merged**
