### PR TITLE
BUG: When scaling a page, reset the cropBox to match the new mediaBox

### PR DESCRIPTION
**Pull request by BrianPainter**
When a page is scaled, shouldn't the cropBox scale at the same rate as the mediaBox? If the cropBox is not changed, then we end up with a "zoomed in" view of the PDF page (if we were scaling to a larger size).

### CODE REVIEW

**Comment by ggicci** [comment]
The `cropBox` and `mediaBox` can be different. I guess you are trying to scale the `cropBox` by the same factor the `mediaBox` has scaled?

**Comment by MartinThoma** [comment]
Thank you for the contribution :-)

**Comment by MartinThoma** [comment]
Reminds me of https://github.com/py-pdf/PyPDF2/pull/240 :smile:

**Comment by MartinThoma** [comment]
I'm uncertain if this is actually desirable. A unit test which shows the new behavior would be amazing :pray:

**Comment by MartinThoma** [comment]
@BrianPainter @ggicci I've moved the logic to #1066 as PyPDF2 has changed a lot and rebasing would likely be a pain. I would appreciate if you would participate in the discussions there :-) 

Especially, I would like to know what you think about scaling all of the other boxes as well.

**Pull request closed without merging**
