### PR TITLE
Decimal fallback for malformed PDFs.

### PR DESCRIPTION
**Pull request by jcampbell05**
Fixes https://github.com/mstamy2/PyPDF2/issues/386

### CODE REVIEW

**Comment by pupca** [comment]
Why is this not merged yet?

**Comment by MartinThoma** [comment]
@jcampbell05 Would you mind to open a new PR with only the changes in `generic.py`? That one I would merge immediately. I'm uncertain about the changes in `pdf.py`.

If you don't have the time for that, I would do it myself + add you as a co-author in the commit message to give you attribution.

**Comment by MartinThoma** [comment]
https://github.com/py-pdf/PyPDF2/pull/782 was merged and will be part of the next release :+1:

**Comment by MartinThoma** [comment]
Closing here as this was merged in another PR

**Pull request closed without merging**
