### PR TITLE
BUG : Merger to be initialize with strict=False default

### PR DESCRIPTION
**Pull request by pubpub-zz**
tracked in
https://github.com/mvicenzi/pdf_tools/issues/2

as said in title

### CODE REVIEW

**Comment by MartinThoma** [comment]
Thank you!

**Comment by MartinThoma** [comment]
... damn, that merge was actually wrong. The "deprecations" branch will be merged into `main`. No breaking changes should happen there.

But I do want to change the behavior for PyPDF2 2.0.0

**Comment by pubpub-zz** [comment]
> But I do want to change the behavior for PyPDF2 2.0.0

@MartinThoma  can you please clarify your thoughts?

**Comment by MartinThoma** [comment]
I want to say that changing the default is not acceptable in PyPDF2 1.x, but I definitely want to have this change with PyPDF2 2.0.0 (I actually thought I had added it there already)

**Comment by MartinThoma** [comment]
I have a nice idea! We leave the new `strict=False` default in the `PdfMerger`, but for users of the `PdfFileMerger` the default stays at `strict=True`. This way I don't need to make a major version bump while still being able to move into this direction :-) (with a notice in the changelog, of course :-) )

**Comment by MartinThoma** [comment]
Here is what I meant: https://github.com/py-pdf/PyPDF2/pull/867/commits/ba6a427dc237968ce5dbd39f56ec12e4edbd6e60

**Pull request merged**
